INSERT INTO categories(id, name, description, version) VALUES (1, 'Fish', 'Any of numerous cold-blooded aquatic vertebrates characteristically having fins, gills, and a streamlined body', 1)
INSERT INTO categories(id, name, description, version) VALUES (2, 'Dogs', 'A domesticated carnivorous mammal related to the foxes and wolves and raised in a wide variety of breeds', 1)
INSERT INTO categories(id, name, description, version) VALUES (3, 'Reptiles', 'Any of various cold-blooded, usually egg-laying vertebrates, such as a snake, lizard, crocodile, turtle', 1)
INSERT INTO categories(id, name, description, version) VALUES (4, 'Cats', ' Small carnivorous mammal domesticated since early times as a catcher of rats and mice and as a pet and existing in several distinctive breeds and varieties', 1)
INSERT INTO categories(id, name, description, version) VALUES (5, 'Birds', 'Any of the class Aves of warm-blooded, egg-laying, feathered vertebrates with forelimbs modified to form wings', 1)
